# Generated by Django 5.1.1 on 2024-10-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_feature_alter_offer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='features',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='title',
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('revisions', models.IntegerField()),
                ('delivery_time_in_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_type', models.CharField(max_length=10)),
                ('features', models.ManyToManyField(related_name='features_set', to='offer.feature')),
            ],
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='detail_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.detail'),
            preserve_default=False,
        ),
    ]
