# Generated by Django 5.1.1 on 2024-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
