# Generated by Django 5.1.1 on 2024-10-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_detail_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='offer_type',
            field=models.CharField(max_length=10),
        ),
    ]
