# Generated by Django 5.1.1 on 2024-10-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_detail_offer_type'),
        ('userprofile', '0002_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
