# Generated by Django 5.1.1 on 2024-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetails',
            name='features',
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
