# Generated by Django 5.1.1 on 2024-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_remove_offerdetails_features_offerdetails_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
