# Generated by Django 5.1.1 on 2024-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_alter_offer_created_at_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
