# Generated by Django 5.1.1 on 2024-10-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_remove_offerdetails_features_offerdetails_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='delivery_time_in_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='revisions',
            field=models.IntegerField(),
        ),
    ]
