# Generated by Django 5.1.1 on 2024-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_alter_detail_price_alter_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.CharField(max_length=10),
        ),
    ]
