# Generated by Django 5.1.1 on 2024-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_alter_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(to='offer.offerdetails'),
        ),
    ]
