# Generated by Django 5.1.1 on 2024-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_offer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(blank=True, to='offer.offerdetails'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
