# Generated by Django 5.1.1 on 2024-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_offer_min_delivery_time_alter_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.ManyToManyField(to='offer.offerdetails'),
        ),
    ]
