# Generated by Django 5.1.1 on 2024-10-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_remove_offer_details_details_features_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
