# Generated by Django 5.1.1 on 2024-10-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_rename_details_detail_rename_features_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offer.offer'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='offer.detail'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
