# Generated by Django 5.1.1 on 2024-10-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_alter_detail_offer_alter_feature_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
