# Generated by Django 5.1.1 on 2024-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_alter_detail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
