# Generated by Django 5.1.1 on 2024-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_alter_detail_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='features',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.ManyToManyField(to='offer.detail')),
            ],
        ),
    ]
