# Generated by Django 5.1.1 on 2024-10-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_remove_detail_features_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='details',
        ),
        migrations.AddField(
            model_name='detail',
            name='details',
            field=models.ManyToManyField(to='offer.feature'),
        ),
    ]
