# Generated by Django 5.1.1 on 2024-10-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0021_remove_feature_details_detail_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='details',
            new_name='features',
        ),
    ]
