# Generated by Django 5.1.1 on 2024-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0023_remove_detail_features_feature_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='details',
        ),
        migrations.AddField(
            model_name='detail',
            name='features',
            field=models.ManyToManyField(to='offer.feature'),
        ),
    ]
