# Generated by Django 5.1.1 on 2024-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0024_remove_feature_details_detail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='features',
            field=models.ManyToManyField(related_name='details', to='offer.feature'),
        ),
    ]
