# Generated by Django 5.1.1 on 2024-10-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/userprofile/')),
                ('location', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('working_hours', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
