# Generated by Django 5.1.1 on 2024-10-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('bu', 'business'), ('cu', 'customer')], default='cu', max_length=20),
        ),
    ]
