# Generated by Django 5.1.1 on 2024-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('customer', 'customer')], default='customer', max_length=20),
        ),
    ]
