# Generated by Django 5.1.1 on 2024-10-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_business_user', to='userprofile.userprofile')),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer_user', to='userprofile.userprofile')),
            ],
        ),
    ]
