# Generated by Django 5.1.1 on 2024-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_id_order_detail_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRO', 'in_progress'), ('COM', 'completed')], default='PRO', max_length=30),
        ),
    ]
