# Generated by Django 5.1.1 on 2024-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', max_length=30),
        ),
    ]
